// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftcache.proto

package raftcache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node_Statuses int32

const (
	Node_ALONE        Node_Statuses = 0
	Node_INGROUP      Node_Statuses = 1
	Node_DISCONNECTED Node_Statuses = 2
)

var Node_Statuses_name = map[int32]string{
	0: "ALONE",
	1: "INGROUP",
	2: "DISCONNECTED",
}

var Node_Statuses_value = map[string]int32{
	"ALONE":        0,
	"INGROUP":      1,
	"DISCONNECTED": 2,
}

func (x Node_Statuses) String() string {
	return proto.EnumName(Node_Statuses_name, int32(x))
}

func (Node_Statuses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{0, 0}
}

type JoinResp_Results int32

const (
	JoinResp_SUCCESS       JoinResp_Results = 0
	JoinResp_ALREADYJOINED JoinResp_Results = 1
	JoinResp_REJECTED      JoinResp_Results = 2
)

var JoinResp_Results_name = map[int32]string{
	0: "SUCCESS",
	1: "ALREADYJOINED",
	2: "REJECTED",
}

var JoinResp_Results_value = map[string]int32{
	"SUCCESS":       0,
	"ALREADYJOINED": 1,
	"REJECTED":      2,
}

func (x JoinResp_Results) String() string {
	return proto.EnumName(JoinResp_Results_name, int32(x))
}

func (JoinResp_Results) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{1, 0}
}

type Node struct {
	Group                string        `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	ListenAddr           string        `protobuf:"bytes,2,opt,name=ListenAddr,proto3" json:"ListenAddr,omitempty"`
	Status               Node_Statuses `protobuf:"varint,3,opt,name=Status,proto3,enum=raftcache.Node_Statuses" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Node) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Node) GetStatus() Node_Statuses {
	if m != nil {
		return m.Status
	}
	return Node_ALONE
}

type JoinResp struct {
	Result               JoinResp_Results `protobuf:"varint,1,opt,name=Result,proto3,enum=raftcache.JoinResp_Results" json:"Result,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	GroupNodes           []*Node          `protobuf:"bytes,3,rep,name=GroupNodes,proto3" json:"GroupNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{1}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetResult() JoinResp_Results {
	if m != nil {
		return m.Result
	}
	return JoinResp_SUCCESS
}

func (m *JoinResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JoinResp) GetGroupNodes() []*Node {
	if m != nil {
		return m.GroupNodes
	}
	return nil
}

type LeaveResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveResp) Reset()         { *m = LeaveResp{} }
func (m *LeaveResp) String() string { return proto.CompactTextString(m) }
func (*LeaveResp) ProtoMessage()    {}
func (*LeaveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{2}
}

func (m *LeaveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveResp.Unmarshal(m, b)
}
func (m *LeaveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveResp.Marshal(b, m, deterministic)
}
func (m *LeaveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveResp.Merge(m, src)
}
func (m *LeaveResp) XXX_Size() int {
	return xxx_messageInfo_LeaveResp.Size(m)
}
func (m *LeaveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("raftcache.Node_Statuses", Node_Statuses_name, Node_Statuses_value)
	proto.RegisterEnum("raftcache.JoinResp_Results", JoinResp_Results_name, JoinResp_Results_value)
	proto.RegisterType((*Node)(nil), "raftcache.Node")
	proto.RegisterType((*JoinResp)(nil), "raftcache.JoinResp")
	proto.RegisterType((*LeaveResp)(nil), "raftcache.LeaveResp")
}

func init() { proto.RegisterFile("raftcache.proto", fileDescriptor_f886bd89b3f134d3) }

var fileDescriptor_f886bd89b3f134d3 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x3b, 0xfc, 0xef, 0x85, 0x0f, 0xfa, 0x5d, 0x59, 0x34, 0x9a, 0x18, 0xd2, 0x15, 0xab,
	0x4a, 0x8a, 0x89, 0xeb, 0xa6, 0x9d, 0x10, 0x48, 0x6d, 0xcd, 0x54, 0x16, 0x2e, 0x2b, 0x0c, 0x4a,
	0xa2, 0x94, 0x74, 0x06, 0x9f, 0xc8, 0x37, 0xf1, 0xc5, 0xcc, 0x94, 0x16, 0x1b, 0x74, 0x79, 0xcf,
	0x3d, 0x73, 0xcf, 0xf9, 0x65, 0x60, 0x90, 0x25, 0x1b, 0xb9, 0x4a, 0x56, 0xaf, 0xdc, 0xde, 0x67,
	0xa9, 0x4c, 0x51, 0x3f, 0x09, 0xd6, 0x27, 0x81, 0x46, 0x98, 0xae, 0x39, 0x0e, 0xa1, 0x39, 0xcb,
	0xd2, 0xc3, 0xde, 0x24, 0x23, 0x32, 0xd6, 0xd9, 0x71, 0xc0, 0x6b, 0x80, 0x60, 0x2b, 0x24, 0xdf,
	0xb9, 0xeb, 0x75, 0x66, 0xd6, 0xf2, 0x55, 0x45, 0xc1, 0x09, 0xb4, 0x62, 0x99, 0xc8, 0x83, 0x30,
	0xeb, 0x23, 0x32, 0xee, 0x3b, 0xa6, 0xfd, 0x93, 0xa5, 0xce, 0xda, 0xc7, 0x2d, 0x17, 0xac, 0xf0,
	0x59, 0xb7, 0xd0, 0x29, 0x35, 0xd4, 0xa1, 0xe9, 0x06, 0x51, 0x48, 0x0d, 0x0d, 0xbb, 0xd0, 0x9e,
	0x87, 0x33, 0x16, 0x2d, 0x1f, 0x0c, 0x82, 0x06, 0xf4, 0xfc, 0x79, 0xec, 0x45, 0x61, 0x48, 0xbd,
	0x47, 0xea, 0x1b, 0x35, 0xeb, 0x8b, 0x40, 0x67, 0x91, 0x6e, 0x77, 0x8c, 0x8b, 0x3d, 0x4e, 0xa1,
	0xc5, 0xb8, 0x38, 0xbc, 0xc9, 0xbc, 0x6b, 0xdf, 0xb9, 0xaa, 0x84, 0x96, 0x26, 0xfb, 0xe8, 0x10,
	0xac, 0xb0, 0xa2, 0x09, 0xed, 0x7b, 0x2e, 0x44, 0xf2, 0xc2, 0x0b, 0x8c, 0x72, 0xc4, 0x1b, 0x80,
	0x1c, 0x56, 0xf5, 0x55, 0x1c, 0xf5, 0x71, 0xd7, 0x19, 0x9c, 0x71, 0xb0, 0x8a, 0xc5, 0xba, 0x83,
	0x76, 0x71, 0x5d, 0xd5, 0x8e, 0x97, 0x9e, 0x47, 0xe3, 0xd8, 0xd0, 0xf0, 0x3f, 0xfc, 0x73, 0x03,
	0x46, 0x5d, 0xff, 0x69, 0x11, 0xcd, 0x43, 0xea, 0x1b, 0x04, 0x7b, 0xd0, 0x61, 0x74, 0x51, 0x52,
	0x74, 0x41, 0x0f, 0x78, 0xf2, 0xc1, 0x55, 0x41, 0xe7, 0x1d, 0x74, 0x96, 0x6c, 0xa4, 0xa7, 0x32,
	0xd0, 0x86, 0x86, 0x6a, 0x8e, 0xe7, 0xb9, 0x97, 0x17, 0x7f, 0xb0, 0x59, 0x1a, 0x4e, 0xa0, 0x99,
	0x5f, 0xfa, 0xfd, 0x60, 0x58, 0x11, 0x4e, 0x61, 0x96, 0xf6, 0xdc, 0xca, 0xbf, 0x7e, 0xfa, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x46, 0xe0, 0x97, 0x51, 0x0d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftCacheClient is the client API for RaftCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftCacheClient interface {
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error)
	Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error)
}

type raftCacheClient struct {
	cc *grpc.ClientConn
}

func NewRaftCacheClient(cc *grpc.ClientConn) RaftCacheClient {
	return &raftCacheClient{cc}
}

func (c *raftCacheClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error) {
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error) {
	out := new(LeaveResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftCacheServer is the server API for RaftCache service.
type RaftCacheServer interface {
	Join(context.Context, *Node) (*JoinResp, error)
	Leave(context.Context, *Node) (*LeaveResp, error)
}

// UnimplementedRaftCacheServer can be embedded to have forward compatible implementations.
type UnimplementedRaftCacheServer struct {
}

func (*UnimplementedRaftCacheServer) Join(ctx context.Context, req *Node) (*JoinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedRaftCacheServer) Leave(ctx context.Context, req *Node) (*LeaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}

func RegisterRaftCacheServer(s *grpc.Server, srv RaftCacheServer) {
	s.RegisterService(&_RaftCache_serviceDesc, srv)
}

func _RaftCache_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Leave(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftCache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raftcache.RaftCache",
	HandlerType: (*RaftCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _RaftCache_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _RaftCache_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raftcache.proto",
}
