// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftcache.proto

package raftcache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node_Statuses int32

const (
	Node_ALONE        Node_Statuses = 0
	Node_INGROUP      Node_Statuses = 1
	Node_DISCONNECTED Node_Statuses = 2
	Node_INITIATING   Node_Statuses = 3
	Node_HANDSHAKING  Node_Statuses = 4
)

var Node_Statuses_name = map[int32]string{
	0: "ALONE",
	1: "INGROUP",
	2: "DISCONNECTED",
	3: "INITIATING",
	4: "HANDSHAKING",
}

var Node_Statuses_value = map[string]int32{
	"ALONE":        0,
	"INGROUP":      1,
	"DISCONNECTED": 2,
	"INITIATING":   3,
	"HANDSHAKING":  4,
}

func (x Node_Statuses) String() string {
	return proto.EnumName(Node_Statuses_name, int32(x))
}

func (Node_Statuses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{1, 0}
}

type JoinResp_Results int32

const (
	JoinResp_SUCCESS       JoinResp_Results = 0
	JoinResp_ALREADYJOINED JoinResp_Results = 1
	JoinResp_REJECTED      JoinResp_Results = 2
	JoinResp_PINGFAIL      JoinResp_Results = 3
	JoinResp_TRYLATER      JoinResp_Results = 4
)

var JoinResp_Results_name = map[int32]string{
	0: "SUCCESS",
	1: "ALREADYJOINED",
	2: "REJECTED",
	3: "PINGFAIL",
	4: "TRYLATER",
}

var JoinResp_Results_value = map[string]int32{
	"SUCCESS":       0,
	"ALREADYJOINED": 1,
	"REJECTED":      2,
	"PINGFAIL":      3,
	"TRYLATER":      4,
}

func (x JoinResp_Results) String() string {
	return proto.EnumName(JoinResp_Results_name, int32(x))
}

func (JoinResp_Results) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{2, 0}
}

type LeaveResp_Results int32

const (
	LeaveResp_SUCCESS    LeaveResp_Results = 0
	LeaveResp_REJECTED   LeaveResp_Results = 1
	LeaveResp_NOTINGROUP LeaveResp_Results = 2
)

var LeaveResp_Results_name = map[int32]string{
	0: "SUCCESS",
	1: "REJECTED",
	2: "NOTINGROUP",
}

var LeaveResp_Results_value = map[string]int32{
	"SUCCESS":    0,
	"REJECTED":   1,
	"NOTINGROUP": 2,
}

func (x LeaveResp_Results) String() string {
	return proto.EnumName(LeaveResp_Results_name, int32(x))
}

func (LeaveResp_Results) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{3, 0}
}

type HandshakeResp_Results int32

const (
	HandshakeResp_SUCCESS  HandshakeResp_Results = 0
	HandshakeResp_PINGFAIL HandshakeResp_Results = 1
	HandshakeResp_TRYLATER HandshakeResp_Results = 2
)

var HandshakeResp_Results_name = map[int32]string{
	0: "SUCCESS",
	1: "PINGFAIL",
	2: "TRYLATER",
}

var HandshakeResp_Results_value = map[string]int32{
	"SUCCESS":  0,
	"PINGFAIL": 1,
	"TRYLATER": 2,
}

func (x HandshakeResp_Results) String() string {
	return proto.EnumName(HandshakeResp_Results_name, int32(x))
}

func (HandshakeResp_Results) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{4, 0}
}

type HandshakeConfirmResp_Results int32

const (
	HandshakeConfirmResp_SUCCESS HandshakeConfirmResp_Results = 0
	HandshakeConfirmResp_FAILED  HandshakeConfirmResp_Results = 1
)

var HandshakeConfirmResp_Results_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}

var HandshakeConfirmResp_Results_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x HandshakeConfirmResp_Results) String() string {
	return proto.EnumName(HandshakeConfirmResp_Results_name, int32(x))
}

func (HandshakeConfirmResp_Results) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{5, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Node struct {
	Group                string        `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	ListenAddr           string        `protobuf:"bytes,2,opt,name=ListenAddr,proto3" json:"ListenAddr,omitempty"`
	Status               Node_Statuses `protobuf:"varint,3,opt,name=Status,proto3,enum=raftcache.Node_Statuses" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Node) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Node) GetStatus() Node_Statuses {
	if m != nil {
		return m.Status
	}
	return Node_ALONE
}

type JoinResp struct {
	Result               JoinResp_Results `protobuf:"varint,1,opt,name=Result,proto3,enum=raftcache.JoinResp_Results" json:"Result,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	GroupNodes           []*Node          `protobuf:"bytes,3,rep,name=GroupNodes,proto3" json:"GroupNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{2}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetResult() JoinResp_Results {
	if m != nil {
		return m.Result
	}
	return JoinResp_SUCCESS
}

func (m *JoinResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JoinResp) GetGroupNodes() []*Node {
	if m != nil {
		return m.GroupNodes
	}
	return nil
}

type LeaveResp struct {
	Result               LeaveResp_Results `protobuf:"varint,1,opt,name=Result,proto3,enum=raftcache.LeaveResp_Results" json:"Result,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LeaveResp) Reset()         { *m = LeaveResp{} }
func (m *LeaveResp) String() string { return proto.CompactTextString(m) }
func (*LeaveResp) ProtoMessage()    {}
func (*LeaveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{3}
}

func (m *LeaveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveResp.Unmarshal(m, b)
}
func (m *LeaveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveResp.Marshal(b, m, deterministic)
}
func (m *LeaveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveResp.Merge(m, src)
}
func (m *LeaveResp) XXX_Size() int {
	return xxx_messageInfo_LeaveResp.Size(m)
}
func (m *LeaveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveResp proto.InternalMessageInfo

func (m *LeaveResp) GetResult() LeaveResp_Results {
	if m != nil {
		return m.Result
	}
	return LeaveResp_SUCCESS
}

func (m *LeaveResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HandshakeResp struct {
	Result               HandshakeResp_Results `protobuf:"varint,1,opt,name=Result,proto3,enum=raftcache.HandshakeResp_Results" json:"Result,omitempty"`
	Message              string                `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HandshakeResp) Reset()         { *m = HandshakeResp{} }
func (m *HandshakeResp) String() string { return proto.CompactTextString(m) }
func (*HandshakeResp) ProtoMessage()    {}
func (*HandshakeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{4}
}

func (m *HandshakeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResp.Unmarshal(m, b)
}
func (m *HandshakeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResp.Marshal(b, m, deterministic)
}
func (m *HandshakeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResp.Merge(m, src)
}
func (m *HandshakeResp) XXX_Size() int {
	return xxx_messageInfo_HandshakeResp.Size(m)
}
func (m *HandshakeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResp.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResp proto.InternalMessageInfo

func (m *HandshakeResp) GetResult() HandshakeResp_Results {
	if m != nil {
		return m.Result
	}
	return HandshakeResp_SUCCESS
}

func (m *HandshakeResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HandshakeConfirmResp struct {
	Result               HandshakeConfirmResp_Results `protobuf:"varint,1,opt,name=Result,proto3,enum=raftcache.HandshakeConfirmResp_Results" json:"Result,omitempty"`
	Message              string                       `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *HandshakeConfirmResp) Reset()         { *m = HandshakeConfirmResp{} }
func (m *HandshakeConfirmResp) String() string { return proto.CompactTextString(m) }
func (*HandshakeConfirmResp) ProtoMessage()    {}
func (*HandshakeConfirmResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{5}
}

func (m *HandshakeConfirmResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeConfirmResp.Unmarshal(m, b)
}
func (m *HandshakeConfirmResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeConfirmResp.Marshal(b, m, deterministic)
}
func (m *HandshakeConfirmResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeConfirmResp.Merge(m, src)
}
func (m *HandshakeConfirmResp) XXX_Size() int {
	return xxx_messageInfo_HandshakeConfirmResp.Size(m)
}
func (m *HandshakeConfirmResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeConfirmResp.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeConfirmResp proto.InternalMessageInfo

func (m *HandshakeConfirmResp) GetResult() HandshakeConfirmResp_Results {
	if m != nil {
		return m.Result
	}
	return HandshakeConfirmResp_SUCCESS
}

func (m *HandshakeConfirmResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("raftcache.Node_Statuses", Node_Statuses_name, Node_Statuses_value)
	proto.RegisterEnum("raftcache.JoinResp_Results", JoinResp_Results_name, JoinResp_Results_value)
	proto.RegisterEnum("raftcache.LeaveResp_Results", LeaveResp_Results_name, LeaveResp_Results_value)
	proto.RegisterEnum("raftcache.HandshakeResp_Results", HandshakeResp_Results_name, HandshakeResp_Results_value)
	proto.RegisterEnum("raftcache.HandshakeConfirmResp_Results", HandshakeConfirmResp_Results_name, HandshakeConfirmResp_Results_value)
	proto.RegisterType((*Empty)(nil), "raftcache.Empty")
	proto.RegisterType((*Node)(nil), "raftcache.Node")
	proto.RegisterType((*JoinResp)(nil), "raftcache.JoinResp")
	proto.RegisterType((*LeaveResp)(nil), "raftcache.LeaveResp")
	proto.RegisterType((*HandshakeResp)(nil), "raftcache.HandshakeResp")
	proto.RegisterType((*HandshakeConfirmResp)(nil), "raftcache.HandshakeConfirmResp")
}

func init() { proto.RegisterFile("raftcache.proto", fileDescriptor_f886bd89b3f134d3) }

var fileDescriptor_f886bd89b3f134d3 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0xbd, 0xfc, 0xf7, 0x40, 0x60, 0x3b, 0xe5, 0x60, 0xa5, 0x55, 0x8b, 0xf6, 0x52, 0x0e,
	0x15, 0x8d, 0x48, 0x0e, 0xb9, 0x55, 0x96, 0x71, 0xc0, 0xd4, 0x5d, 0xd0, 0xda, 0x1c, 0x72, 0x74,
	0x83, 0x49, 0x50, 0x1b, 0x8c, 0xb0, 0xa9, 0xd4, 0xc7, 0xe8, 0xa1, 0xea, 0xa9, 0x8f, 0xd3, 0xe7,
	0xe8, 0xab, 0x54, 0x6b, 0xc0, 0x75, 0x0c, 0xa8, 0xc9, 0x71, 0x67, 0xbf, 0xdd, 0xfd, 0x7d, 0xdf,
	0x8c, 0x0d, 0x8d, 0x95, 0x37, 0x8b, 0x6e, 0xbc, 0x9b, 0x3b, 0xbf, 0xb3, 0x5c, 0x05, 0x51, 0x80,
	0x6a, 0x52, 0x60, 0x65, 0x28, 0x9a, 0xf7, 0xcb, 0xe8, 0x1b, 0xfb, 0x4d, 0xa0, 0xc0, 0x83, 0xa9,
	0x8f, 0x4d, 0x28, 0xf6, 0x57, 0xc1, 0x7a, 0xa9, 0x91, 0x16, 0x69, 0xab, 0x62, 0xb3, 0xc0, 0x57,
	0x00, 0xf6, 0x3c, 0x8c, 0xfc, 0x85, 0x3e, 0x9d, 0xae, 0xb4, 0x5c, 0xbc, 0x95, 0xaa, 0xe0, 0x19,
	0x94, 0x9c, 0xc8, 0x8b, 0xd6, 0xa1, 0x96, 0x6f, 0x91, 0x76, 0xbd, 0xab, 0x75, 0xfe, 0x3d, 0x2a,
	0xaf, 0xed, 0x6c, 0x76, 0xfd, 0x50, 0x6c, 0x75, 0x6c, 0x02, 0x95, 0x5d, 0x0d, 0x55, 0x28, 0xea,
	0xf6, 0x88, 0x9b, 0x54, 0xc1, 0x2a, 0x94, 0x2d, 0xde, 0x17, 0xa3, 0xc9, 0x98, 0x12, 0xa4, 0x50,
	0xeb, 0x59, 0x8e, 0x31, 0xe2, 0xdc, 0x34, 0x5c, 0xb3, 0x47, 0x73, 0x58, 0x07, 0xb0, 0xb8, 0xe5,
	0x5a, 0xba, 0x6b, 0xf1, 0x3e, 0xcd, 0x63, 0x03, 0xaa, 0x03, 0x9d, 0xf7, 0x9c, 0x81, 0xfe, 0x41,
	0x16, 0x0a, 0xec, 0x0f, 0x81, 0xca, 0x30, 0x98, 0x2f, 0x84, 0x1f, 0x2e, 0xf1, 0x1c, 0x4a, 0xc2,
	0x0f, 0xd7, 0x5f, 0xa2, 0xd8, 0x4c, 0xbd, 0xfb, 0x22, 0x45, 0xb5, 0x13, 0x75, 0x36, 0x8a, 0x50,
	0x6c, 0xa5, 0xa8, 0x41, 0xf9, 0xa3, 0x1f, 0x86, 0xde, 0xad, 0xbf, 0xf5, 0xb9, 0x5b, 0xe2, 0x3b,
	0x80, 0x38, 0x0d, 0x69, 0x48, 0x1a, 0xcd, 0xb7, 0xab, 0xdd, 0x46, 0xc6, 0xa8, 0x48, 0x49, 0x98,
	0x03, 0xe5, 0xed, 0xed, 0xd2, 0x97, 0x33, 0x31, 0x0c, 0xd3, 0x71, 0xa8, 0x82, 0xcf, 0xe0, 0x44,
	0xb7, 0x85, 0xa9, 0xf7, 0xae, 0x87, 0x23, 0x8b, 0x9b, 0x3d, 0x4a, 0xb0, 0x06, 0x15, 0x61, 0x0e,
	0x77, 0x36, 0x6b, 0x50, 0x19, 0x5b, 0xbc, 0x7f, 0xa5, 0x5b, 0x36, 0xcd, 0xcb, 0x95, 0x2b, 0xae,
	0x6d, 0xdd, 0x35, 0x05, 0x2d, 0xb0, 0xef, 0x04, 0x54, 0xdb, 0xf7, 0xbe, 0xfa, 0xb1, 0xc5, 0x8b,
	0x8c, 0xc5, 0x97, 0x29, 0x9e, 0x44, 0xf5, 0x78, 0x8f, 0xec, 0xe2, 0x08, 0x72, 0x9a, 0x8f, 0xc8,
	0x36, 0xf0, 0x91, 0xbb, 0x6b, 0x54, 0x8e, 0xfd, 0x24, 0x70, 0x32, 0xf0, 0x16, 0xd3, 0xf0, 0xce,
	0xfb, 0xbc, 0xe1, 0xba, 0xcc, 0x70, 0xb5, 0x52, 0x5c, 0x0f, 0x94, 0x4f, 0x60, 0xeb, 0x1e, 0x67,
	0x4b, 0xd2, 0x22, 0x0f, 0xd2, 0xca, 0xb1, 0x1f, 0x04, 0x9a, 0xc9, 0x7b, 0x46, 0xb0, 0x98, 0xcd,
	0x57, 0xf7, 0x31, 0xe0, 0xfb, 0x0c, 0xe0, 0x9b, 0x43, 0x80, 0xa9, 0x03, 0x4f, 0xe0, 0x64, 0x47,
	0x38, 0x01, 0x4a, 0x92, 0x51, 0x26, 0xd8, 0xfd, 0x95, 0x03, 0x55, 0x78, 0xb3, 0xc8, 0x90, 0x0f,
	0xe2, 0x5b, 0x28, 0x8c, 0xe7, 0x8b, 0x5b, 0xa4, 0x29, 0x88, 0xf8, 0xbb, 0x3c, 0xdd, 0xab, 0x30,
	0x05, 0x3b, 0x50, 0x90, 0xd3, 0x8b, 0xd9, 0xd9, 0x3b, 0x7d, 0x7e, 0x60, 0xbe, 0x99, 0x82, 0x67,
	0x50, 0x8c, 0x47, 0x61, 0xff, 0x40, 0xf3, 0xd0, 0xb4, 0x30, 0x05, 0x2f, 0x41, 0x4d, 0x32, 0xd8,
	0x3f, 0xa5, 0x1d, 0xeb, 0x25, 0x53, 0xf0, 0x0a, 0x68, 0x36, 0xbd, 0xfd, 0x0b, 0x5e, 0xff, 0x27,
	0x6b, 0xa6, 0x7c, 0x2a, 0xc5, 0xbf, 0xaa, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0xfa,
	0x26, 0x3d, 0xbd, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftCacheClient is the client API for RaftCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftCacheClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error)
	Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error)
	Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResp, error)
	HandshakeConfirm(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeConfirmResp, error)
}

type raftCacheClient struct {
	cc *grpc.ClientConn
}

func NewRaftCacheClient(cc *grpc.ClientConn) RaftCacheClient {
	return &raftCacheClient{cc}
}

func (c *raftCacheClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error) {
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error) {
	out := new(LeaveResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Handshake(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeResp, error) {
	out := new(HandshakeResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) HandshakeConfirm(ctx context.Context, in *Node, opts ...grpc.CallOption) (*HandshakeConfirmResp, error) {
	out := new(HandshakeConfirmResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/HandshakeConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftCacheServer is the server API for RaftCache service.
type RaftCacheServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	Join(context.Context, *Node) (*JoinResp, error)
	Leave(context.Context, *Node) (*LeaveResp, error)
	Handshake(context.Context, *Node) (*HandshakeResp, error)
	HandshakeConfirm(context.Context, *Node) (*HandshakeConfirmResp, error)
}

// UnimplementedRaftCacheServer can be embedded to have forward compatible implementations.
type UnimplementedRaftCacheServer struct {
}

func (*UnimplementedRaftCacheServer) Ping(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedRaftCacheServer) Join(ctx context.Context, req *Node) (*JoinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedRaftCacheServer) Leave(ctx context.Context, req *Node) (*LeaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (*UnimplementedRaftCacheServer) Handshake(ctx context.Context, req *Node) (*HandshakeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (*UnimplementedRaftCacheServer) HandshakeConfirm(ctx context.Context, req *Node) (*HandshakeConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandshakeConfirm not implemented")
}

func RegisterRaftCacheServer(s *grpc.Server, srv RaftCacheServer) {
	s.RegisterService(&_RaftCache_serviceDesc, srv)
}

func _RaftCache_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Leave(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Handshake(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_HandshakeConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).HandshakeConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/HandshakeConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).HandshakeConfirm(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftCache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raftcache.RaftCache",
	HandlerType: (*RaftCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RaftCache_Ping_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _RaftCache_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _RaftCache_Leave_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _RaftCache_Handshake_Handler,
		},
		{
			MethodName: "HandshakeConfirm",
			Handler:    _RaftCache_HandshakeConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raftcache.proto",
}
