// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftcache.proto

package raftcache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	AdminAddr            string   `protobuf:"bytes,1,opt,name=AdminAddr,proto3" json:"AdminAddr,omitempty"`
	ServeAddr            string   `protobuf:"bytes,2,opt,name=ServeAddr,proto3" json:"ServeAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAdminAddr() string {
	if m != nil {
		return m.AdminAddr
	}
	return ""
}

func (m *Node) GetServeAddr() string {
	if m != nil {
		return m.ServeAddr
	}
	return ""
}

type JoinResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{1}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LeaveResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveResp) Reset()         { *m = LeaveResp{} }
func (m *LeaveResp) String() string { return proto.CompactTextString(m) }
func (*LeaveResp) ProtoMessage()    {}
func (*LeaveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f886bd89b3f134d3, []int{2}
}

func (m *LeaveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveResp.Unmarshal(m, b)
}
func (m *LeaveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveResp.Marshal(b, m, deterministic)
}
func (m *LeaveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveResp.Merge(m, src)
}
func (m *LeaveResp) XXX_Size() int {
	return xxx_messageInfo_LeaveResp.Size(m)
}
func (m *LeaveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveResp proto.InternalMessageInfo

func (m *LeaveResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "raftcache.Node")
	proto.RegisterType((*JoinResp)(nil), "raftcache.JoinResp")
	proto.RegisterType((*LeaveResp)(nil), "raftcache.LeaveResp")
}

func init() { proto.RegisterFile("raftcache.proto", fileDescriptor_f886bd89b3f134d3) }

var fileDescriptor_f886bd89b3f134d3 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x4c, 0x2b,
	0x49, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x39, 0x71, 0xb1, 0xf8, 0xe5, 0xa7, 0xa4, 0x0a, 0xc9, 0x70, 0x71, 0x3a, 0xa6, 0xe4, 0x66, 0xe6,
	0x39, 0xa6, 0xa4, 0x14, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x40, 0xb2, 0xc1,
	0xa9, 0x45, 0x65, 0xa9, 0x60, 0x59, 0x26, 0x88, 0x2c, 0x5c, 0x40, 0x49, 0x89, 0x8b, 0xc3, 0x2b,
	0x3f, 0x33, 0x2f, 0x28, 0xb5, 0xb8, 0x40, 0x48, 0x8c, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4,
	0x18, 0x6a, 0x08, 0x94, 0xa7, 0xa4, 0xcc, 0xc5, 0xe9, 0x93, 0x9a, 0x58, 0x96, 0x8a, 0x4f, 0x91,
	0x51, 0x2e, 0x17, 0x67, 0x50, 0x62, 0x5a, 0x89, 0x33, 0xc8, 0x65, 0x42, 0x7a, 0x5c, 0x2c, 0x20,
	0x53, 0x85, 0xf8, 0xf5, 0x10, 0xce, 0x07, 0x39, 0x55, 0x4a, 0x18, 0x49, 0x00, 0x66, 0xaf, 0x12,
	0x83, 0x90, 0x01, 0x17, 0x2b, 0xd8, 0x06, 0x4c, 0x0d, 0x22, 0x48, 0x02, 0x70, 0x47, 0x28, 0x31,
	0x24, 0xb1, 0x81, 0x43, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x39, 0x6f, 0xde, 0x6f, 0x20,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RaftCacheClient is the client API for RaftCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftCacheClient interface {
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error)
	Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error)
}

type raftCacheClient struct {
	cc *grpc.ClientConn
}

func NewRaftCacheClient(cc *grpc.ClientConn) RaftCacheClient {
	return &raftCacheClient{cc}
}

func (c *raftCacheClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*JoinResp, error) {
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*LeaveResp, error) {
	out := new(LeaveResp)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftCacheServer is the server API for RaftCache service.
type RaftCacheServer interface {
	Join(context.Context, *Node) (*JoinResp, error)
	Leave(context.Context, *Node) (*LeaveResp, error)
}

// UnimplementedRaftCacheServer can be embedded to have forward compatible implementations.
type UnimplementedRaftCacheServer struct {
}

func (*UnimplementedRaftCacheServer) Join(ctx context.Context, req *Node) (*JoinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedRaftCacheServer) Leave(ctx context.Context, req *Node) (*LeaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}

func RegisterRaftCacheServer(s *grpc.Server, srv RaftCacheServer) {
	s.RegisterService(&_RaftCache_serviceDesc, srv)
}

func _RaftCache_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Leave(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _RaftCache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raftcache.RaftCache",
	HandlerType: (*RaftCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _RaftCache_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _RaftCache_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raftcache.proto",
}
